apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.mattermost_secret.name }}"
  labels:
    {{- include "mostful-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.mattermost_secret }}
  mentor_add_token: "{{ .mentor_add_token | b64enc }}"
  mentor_remove_token: "{{ .mentor_remove_token | b64enc }}"
  check_me_token: "{{ .check_me_token | b64enc }}"
  mentor_labs_token: "{{ .mentor_labs_token | b64enc }}"
  labs_token: "{{ .labs_token | b64enc }}"
  set_name_token: "{{ .set_name_token | b64enc }}"
  bot_token: "{{ .bot_token | b64enc }}"
  {{- end }}
