apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ include "ttbot.fullname" . }}
  labels:
    {{- include "ttbot.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.database_size }}
