apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ttbot.fullname" . }}-secret
  labels:
    {{- include "ttbot.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values }}
  telegram_token: "{{ .telegram_token | b64enc }}"
  redmine_key: "{{ .redmine_key | b64enc }}"
  {{- end }}
