apiVersion: v1
kind: Service
metadata:
  name: {{ include "ttbot.fullname" . }}
  labels:
    {{- include "ttbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: control
  selector:
    {{- include "ttbot.selectorLabels" . | nindent 4 }}
